server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  user: weex_user
  password: weex_password
  dbname: weex_monitor
  charset: utf8mb4
  parse_time: true
  loc: Local

redis:
  host: localhost
  port: 6379
  db: 0

weex:
  api_url: "https://http-gateway1.janapw.com/api/v1/public/trace/getOpenOrderList"
  timeout: 30s
  retry_times: 3

monitor:
  default_interval: 10s
  max_goroutines: 100

notification:
  webhook_url: ""
  timeout: 10s

log:
  level: info
  format: json
  output: both
